### PR TITLE
Add TOC and other feedback to lab-04.qmd

### PR DESCRIPTION
**Pull request by francojc**

### CODE REVIEW

**Comment by francojc** [comment]
Review the "Files changed" above. If you want to incorporate my suggestions and feedback into your repository. Click the "Merge" button.

**Comment by LINWANG1234** [comment]
@francojc Thanks for your feedback, I will merge pull request. For the subtitle, I just forgot it is already bold font which I did it again .  Using the terminal to use Git and interact with GitHub is something that I explored online, it looks that this part is useless. I will just keep using the RStudio interface.

**Comment by francojc** [comment]
> it looks that this part is useless.

Not really, but a bit more complicated and not recommended for beginners. 😃

**Comment by LINWANG1234** [comment]
@francojc ok, got it. Thanks😄

**Pull request merged**
